name: watchhar
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.2.2
      - cycler==0.12.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - h11==0.14.0
      - h5py==3.6.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - librosa==0.8.1
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - musdb==0.4.2
      - museval==0.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.22.0
      - oauthlib==3.2.2
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.4.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pflops==0.1.5
      - pillow==11.1.0
      - platformdirs==4.3.6
      - portalocker==3.2.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - psutil==6.1.1
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - rsa==4.9
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simplejson==3.19.3
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.10.3.post1
      - soupsieve==2.6
      - stack-data==0.6.3
      - stempeg==0.2.3
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchcontrib==0.0.2
      - torchlibrosa==0.0.9
      - torchmetrics==1.6.1
      - torchvision==0.15.2
      - tornado==6.4.2
      - tqdm==4.62.3
      - traitlets==5.14.3
      - typer==0.9.4
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
      - yarl==1.18.3
